{
    'name': 'Hospital Patient Portal',
    'version': '18.0.1.0',
    'category': 'Healthcare',
    'summary': 'Manage hospital patients and their records',
    'depends': ['base','portal','sms','contacts','calendar','appointment', 'product', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/email_templates.xml',
        'data/sequence.xml',
        'views/menuitems.xml',
        'views/res_partner.xml',
        'views/allergy.xml',
        'views/allergy_question.xml',
        'views/disease.xml',
        'views/disease_question.xml',
        'views/portal_templates.xml',
        'views/patient_visit_views.xml',
        'views/patient_portal_visit_view.xml',
        'views/patient_visit_receipt.xml',
    ],
    'installable': True,
    'application': True,
}
